export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const SET_USERS_REQUESTED = "SET_USERS_REQUESTED";
export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS";
export const SET_USERS_FAILED = "SET_USERS_FAILED";

